const en = {
  recommended: "IVR/IAS Level 1",
  refresher: "IVR/IAS Level 1 refresher",
  emailAction: "Email Monica",
  callAction: "Call Monica",
  metaTitle: "Training enquiries & contact | Swiss Defibrillator",
  metaDescription:
    "Contact Monica Aleman for on-site BLS-AED-SRC training in Switzerland. Request a course quote, ask about AED maintenance or find the right defibrillator.",
  optional: "optional",
  title: "Request training for your team",
  intro:
    "Tell us where, when and how many people you would like to train. Your instructor, Monica Aleman, will help you choose the right course and prepare a quote. For AED sales or maintenance, choose the relevant subject below.",
  profileTitle: "Your instructor, Monica Aleman",
  profile:
    "Monica is an experienced BLS-AED-SRC instructor and adult educator. She personally delivers practical, hands-on training in small groups, helping participants practise how to respond to a cardiac emergency.",
  coverage:
    "Training at your premises throughout Switzerland, for companies, hotels, schools and organisations. Courses are taught in English, French and German.",
  formTitle: "Send an enquiry",
  subject: "What can we help with?",
  training: "BLS-AED-SRC training",
  maintenance: "AED maintenance",
  products: "AED products",
  other: "Other enquiry",
  course: "Course",
  undecided: "Help me choose",
  company: "Company or organisation",
  location: "Town / training location",
  participants: "Number of participants",
  language: "Course language",
  choose: "Please choose",
  english: "English",
  french: "French",
  german: "German",
  timing: "Preferred dates or timing (optional)",
  timingHint: "For example, a weekday morning in November",
  name: "Your name",
  email: "Email address",
  message: "Message",
  optionalMessage: "Anything else we should know? (optional)",
  details:
    "Required fields unless marked optional. One instructor per eight participants; larger teams can request a tailored quote.",
  send: "Send enquiry",
  sending: "Sending…",
  error:
    "Your enquiry could not be sent. Please try again, or contact Monica by phone or email. Your details are still here.",
  success: "Thank you for your enquiry",
  successBody:
    "Your message has been sent. Monica will get back to you about your request.",
  back: "Back to contact",
  privacy: "How we handle your information",
  basic: "BLS-AED-SRC Complet — CHF 890 + VAT / group · 3–4 hours",
  lite: "BLS-AED-SRC Compact — CHF 455 + VAT / group · 1–2 hours",
};
export type EnquiryCopy = typeof en;
export const enquiryCopy: Record<string, EnquiryCopy> = {
  en,
  de: {
    recommended: "IVR/IAS Stufe 1",
    refresher: "IVR/IAS Stufe 1 Refresher",
    emailAction: "E-Mail an Monica",
    callAction: "Monica anrufen",
    metaTitle: "Kursanfragen & Kontakt | Swiss Defibrillator",
    metaDescription:
      "Kontaktieren Sie Monica Aleman für BLS-AED-SRC-Schulungen bei Ihnen vor Ort in der Schweiz. Fragen Sie nach Kursen, AED-Wartung oder Defibrillatoren.",
    optional: "optional",
    title: "Schulung für Ihr Team anfragen",
    intro:
      "Teilen Sie uns Ort, Zeitraum und Teilnehmerzahl mit. Ihre Kursleiterin Monica Aleman unterstützt Sie bei der Kurswahl und erstellt eine Offerte. Für AED-Verkauf oder Wartung wählen Sie unten das passende Thema.",
    profileTitle: "Ihre Kursleiterin Monica Aleman",
    profile:
      "Monica ist eine erfahrene BLS-AED-SRC-Kursleiterin und Erwachsenenbildnerin. Sie führt die praktischen Schulungen in kleinen Gruppen persönlich durch. Die Teilnehmenden üben, wie sie bei einem Herznotfall handeln können.",
    coverage:
      "Schulungen bei Ihnen vor Ort in der ganzen Schweiz, für Unternehmen, Hotels, Schulen und Organisationen. Unterricht auf Deutsch, Französisch und Englisch.",
    formTitle: "Anfrage senden",
    subject: "Wie können wir helfen?",
    training: "BLS-AED-SRC-Schulung",
    maintenance: "AED-Wartung",
    products: "AED-Produkte",
    other: "Andere Anfrage",
    course: "Kurs",
    undecided: "Ich wünsche eine Beratung",
    company: "Unternehmen oder Organisation",
    location: "Ort / Schulungsort",
    participants: "Anzahl Teilnehmende",
    language: "Kurssprache",
    choose: "Bitte auswählen",
    english: "Englisch",
    french: "Französisch",
    german: "Deutsch",
    timing: "Gewünschte Termine oder Zeitraum (optional)",
    timingHint: "Zum Beispiel ein Vormittag unter der Woche im November",
    name: "Ihr Name",
    email: "E-Mail-Adresse",
    message: "Nachricht",
    optionalMessage: "Was sollten wir noch wissen? (optional)",
    details:
      "Pflichtfelder, sofern nicht als optional markiert. Eine Kursleitung pro acht Teilnehmende; für grössere Teams erstellen wir eine individuelle Offerte.",
    send: "Anfrage senden",
    sending: "Wird gesendet…",
    error:
      "Ihre Anfrage konnte nicht gesendet werden. Versuchen Sie es erneut oder kontaktieren Sie Monica telefonisch oder per E-Mail. Ihre Angaben bleiben erhalten.",
    success: "Vielen Dank für Ihre Anfrage",
    successBody:
      "Ihre Nachricht wurde gesendet. Monica wird sich zu Ihrer Anfrage bei Ihnen melden.",
    back: "Zurück zum Kontakt",
    privacy: "So behandeln wir Ihre Daten",
    basic: "BLS-AED-SRC Complet — CHF 890 + MwSt. / Gruppe · 3–4 Stunden",
    lite: "BLS-AED-SRC Compact — CHF 455 + MwSt. / Gruppe · 1–2 Stunden",
  },
  fr: {
    recommended: "IVR/IAS niveau 1",
    refresher: "Recyclage IVR/IAS niveau 1",
    emailAction: "Écrire à Monica",
    callAction: "Appeler Monica",
    metaTitle: "Demandes de formation et contact | Swiss Defibrillator",
    metaDescription:
      "Contactez Monica Aleman pour une formation BLS-AED-SRC dans vos locaux en Suisse. Demandez un devis, des conseils sur la maintenance ou un défibrillateur.",
    optional: "facultatif",
    title: "Demandez une formation pour votre équipe",
    intro:
      "Indiquez le lieu, la période et le nombre de participants. Votre formatrice, Monica Aleman, vous aide à choisir le cours adapté et prépare un devis. Pour la vente ou la maintenance de DAE, choisissez le sujet correspondant ci-dessous.",
    profileTitle: "Votre formatrice, Monica Aleman",
    profile:
      "Monica est une instructrice BLS-AED-SRC expérimentée et une formatrice d’adultes. Elle anime personnellement des formations pratiques en petits groupes, pour que chacun puisse s’exercer à réagir face à une urgence cardiaque.",
    coverage:
      "Formations dans vos locaux, partout en Suisse, pour les entreprises, hôtels, écoles et organisations. Cours en français, allemand et anglais.",
    formTitle: "Envoyer une demande",
    subject: "Comment pouvons-nous vous aider ?",
    training: "Formation BLS-AED-SRC",
    maintenance: "Maintenance de DAE",
    products: "Produits DAE",
    other: "Autre demande",
    course: "Cours",
    undecided: "Aidez-moi à choisir",
    company: "Entreprise ou organisation",
    location: "Ville / lieu de formation",
    participants: "Nombre de participants",
    language: "Langue du cours",
    choose: "Veuillez choisir",
    english: "Anglais",
    french: "Français",
    german: "Allemand",
    timing: "Dates ou période souhaitées (facultatif)",
    timingHint: "Par exemple, un matin en semaine en novembre",
    name: "Votre nom",
    email: "Adresse e-mail",
    message: "Message",
    optionalMessage: "Autres précisions utiles (facultatif)",
    details:
      "Champs obligatoires sauf mention contraire. Un instructeur pour huit participants ; les équipes plus nombreuses peuvent demander un devis adapté.",
    send: "Envoyer la demande",
    sending: "Envoi en cours…",
    error:
      "Votre demande n’a pas pu être envoyée. Réessayez ou contactez Monica par téléphone ou par e-mail. Vos informations sont conservées dans le formulaire.",
    success: "Merci pour votre demande",
    successBody:
      "Votre message a été envoyé. Monica vous recontactera au sujet de votre demande.",
    back: "Retour au contact",
    privacy: "Comment nous traitons vos informations",
    basic: "BLS-AED-SRC Complet — CHF 890 + TVA / groupe · 3–4 heures",
    lite: "BLS-AED-SRC Compact — CHF 455 + TVA / groupe · 1–2 heures",
  },
  it: {
    recommended: "IVR/IAS livello 1",
    refresher: "Aggiornamento IVR/IAS livello 1",
    emailAction: "Scrivi a Monica",
    callAction: "Chiama Monica",
    metaTitle: "Richieste di formazione e contatti | Swiss Defibrillator",
    metaDescription:
      "Contattate Monica Aleman per corsi BLS-AED-SRC presso la vostra sede in Svizzera. Richiedete un preventivo, la manutenzione DAE o un defibrillatore.",
    optional: "facoltativo",
    title: "Richiedete una formazione per il vostro team",
    intro:
      "Indicate luogo, periodo e numero di partecipanti. La vostra istruttrice, Monica Aleman, vi aiuta a scegliere il corso adatto e prepara un preventivo. Per la vendita o la manutenzione di DAE, scegliete l’argomento corrispondente qui sotto.",
    profileTitle: "La vostra istruttrice, Monica Aleman",
    profile:
      "Monica è un’istruttrice BLS-AED-SRC esperta e una formatrice di adulti. Conduce personalmente corsi pratici in piccoli gruppi, aiutando i partecipanti a esercitarsi su come reagire a un’emergenza cardiaca.",
    coverage:
      "Corsi presso la vostra sede in tutta la Svizzera, per aziende, hotel, scuole e organizzazioni. La formazione si svolge in inglese, francese e tedesco.",
    formTitle: "Invia una richiesta",
    subject: "Come possiamo aiutarvi?",
    training: "Formazione BLS-AED-SRC",
    maintenance: "Manutenzione DAE",
    products: "Prodotti DAE",
    other: "Altra richiesta",
    course: "Corso",
    undecided: "Aiutatemi a scegliere",
    company: "Azienda o organizzazione",
    location: "Città / luogo della formazione",
    participants: "Numero di partecipanti",
    language: "Lingua del corso",
    choose: "Selezionare",
    english: "Inglese",
    french: "Francese",
    german: "Tedesco",
    timing: "Date o periodo preferiti (facoltativo)",
    timingHint: "Ad esempio, una mattina infrasettimanale a novembre",
    name: "Nome",
    email: "Indirizzo e-mail",
    message: "Messaggio",
    optionalMessage: "Altre informazioni utili (facoltativo)",
    details:
      "Campi obbligatori salvo diversa indicazione. Un istruttore ogni otto partecipanti; per gruppi più grandi è possibile richiedere un preventivo personalizzato.",
    send: "Invia richiesta",
    sending: "Invio in corso…",
    error:
      "Impossibile inviare la richiesta. Riprovate oppure contattate Monica per telefono o e-mail. I dati rimangono nel modulo.",
    success: "Grazie per la richiesta",
    successBody:
      "Il messaggio è stato inviato. Monica vi ricontatterà in merito alla vostra richiesta.",
    back: "Torna ai contatti",
    privacy: "Come trattiamo i vostri dati",
    basic: "BLS-AED-SRC Complet — CHF 890 + IVA / gruppo · 3–4 ore",
    lite: "BLS-AED-SRC Compact — CHF 455 + IVA / gruppo · 1–2 ore",
  },
};
export function getEnquiryCopy(lang?: string) {
  return enquiryCopy[lang || "en"] || en;
}
